<Project Sdk="Microsoft.NET.Sdk.Worker">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>dotnet-Media8.Workstation.Worker.Ingestion-fcc172f0-101b-477c-8b92-d104aec9ec15</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.9" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\media8-api\src\Media8.Workstation.Domain\Media8.Workstation.Domain.csproj" />
  </ItemGroup>
</Project>
